import type { Metadata } from "next"; 
import "./globals.css";
import { ThemeScript } from "./theme-script";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <ThemeScript />
      <link rel="shortcut icon" href="/img/avatar.png" type="image/x-icon" />
        </head>
      <body
        className={`antialiased bg-[#f1f1f1] dark:bg-[#1f1f1f]`}
      >
        {children}
      </body>
    </html>
  );
}